# Generated by Django 6.0.2 on 2026-05-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDShibrido', '0002_evento_delete_detector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_ip', models.GenericIPAddressField()),
                ('alert_type', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=20)),
            ],
        ),
    ]
