# Generated by Django 6.0.2 on 2026-05-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDShibrido', '0003_alerta'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.IntegerField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
